### ISSUE TITLE
login_as not doing anything

### ISSUE THREAD

**Issue by kiddrew** [hassox/warden#101]
I'm running the following rspec code:

    create :user
    user.should be_valid

    login_as :user 
    current_path.should eq root_path

I'm getting this error:

    Failure/Error: current_path.should eq root_path

      expected: "/"
           got: nil

I'm using devise 3.4.1 which uses warden 1.2.3.  This began with an update recently and I haven't been able to track down which gem is causing it - I'm not sure that this is a warden issue.  Any help?

**Comment by hassox** [comment]
With devise you should use the sign_in helper. The login_as is for raw warden and would accept  a user object not symbol. Devise uses scopes a _lot_ so your login_as, which uses the default scope will not be picked up by devise.
