### ISSUE TITLE
Rack::Lint not allowing non String variables

### ISSUE THREAD

**Issue by joost** [hassox/warden#104]
See https://github.com/rack/rack/blob/master/lib/rack/lint.rb#L274:

```
next  if key.include? "."   # Skip extensions
assert("env variable #{key} has non-string value #{value.inspect}") {
```

I got this assertion since `env['warden']` is the Proxy. Should it be renamed to `env['warden.proxy']`?

**Comment by hassox** [comment]
I'd be down for that. Could you provide a PR?

**Comment by joost** [comment]
Hmm... long time ago.. I cannot really remember when/why I got this error.
When I come by it I will definitely create a PR :)
