### ISSUE TITLE
JWT Support

### ISSUE THREAD

**Issue by hwhelchel** [hassox/warden#106]
Have y'all considered supporting JWT for authentication?

What I envision is providing access to the response headers in the callbacks. Then a hook can be set up to add a JWT in the headers sent back to the client on each response. The client would then use this JWT in the next request. Thanks for a great gem.

**Comment by TiagoCardoso1983** [comment]
Hi all. +1 on this.

I've read some posts regarding this (and devise) and I guess this would involve disregarding the dependency on the sessions middleware. This means that the piece:

```ruby
app.use ::Warden::Manager do |config|
  ...
  config.serialize_into_session { |user| user.id } 
  config.serialize_from_session { |id| ::User.get(id) } 
  config.failure_app = app 
end
```

would have to be completely rethought: not relying on sessions means ```serialize_into/from_session``` are bad names (breaking change). But on the other hand session is only a "store". One could have different "store" strategies, in which one of them could be JWT. 

I'm wondering whether this could be easily bundled into devise, as devise itself doesn't have a clue where the record key and salt are serialized into.

**Comment by TiagoCardoso1983** [comment]
API changes proposal:

config allows one to set the serializer (the following already assumes opting for one and only one serializer per warden middleware):

```ruby
  ...
  # advantage: allows explicitness in choosing the session serialization as default strategy
  # optional first argument: scope
  config.serializer :session, :serialize => -> (user) { user.id  },
                                           :deserialize => -> (id) { User.get(id) }
  ...
```

These callbacks would then be added to the SessionSerializer (which has already default serialize/deserialize methods). 

One could then build different strategies:

```ruby
module Warden
  class JWTSerializer
    def serialize(user)
       JWT.encode({user_id: user}, VERIFY_KEY, "RS256", exp: Time.now.to_i + 3000)
    end

    def deserialize(key)
      payload, header = JWT.decode(key, VERIFY_KEY, true)
      # ... do necessary verifications, token expire, yadayada
      payload["user_id"]
    end

    def store(user, scope)
      return unless user
      method_name = "#{scope}_serialize"
      specialized = respond_to?(method_name)
      token = specialized ? send(method_name, user) : serialize(user)
      @env["HTTP_AUTHORIZATION"] = "#{scope || 'Basic'}: #{token}"
    end

    def fetch(scope)
      lookup = scope ? scope.to_s : "Basic"
      key = @env["HTTP_AUTHORIZATION"][%r/#{lookup}: (.+)/, 1] if @env["HTTP_AUTHORIZATION"] 
session[key_for(scope)]

      return nil unless key

      method_name = "#{scope}_deserialize"
      user = respond_to?(method_name) ? send(method_name, key) : deserialize(key)
      @env.delete("HTTP_AUTHORIZATION") unless user
      user
    end
  end
end
```

**Comment by hassox** [comment]
Support for _reading_ the JWT and setting the user from it is already in Warden. Create a strategy to reads the header, verifies the token and logs in the resource. Providing the JWT to begin with should happen outside warden.

I'd recommend setting the for the user lookup into the "sub" field in the JWT.

**Comment by TiagoCardoso1983** [comment]
@hassox, thx for the answer. And actually wasn't aware of the possibility of overwriting the #store? method within the strategy. Do you know of some gist/devise plugin which already plays around with this? Nevertheless, I'll see if I'll play around with this within the next 2 weeks and will keep you posted.

**Comment by TiagoCardoso1983** [comment]
Confirm it, store marked as false indeed solves the problem. 

> I'd recommend setting the for the user lookup into the "sub" field in the JWT.

What do you exactly mean by "sub" field?

**Comment by hwhelchel** [comment]
The subject: https://github.com/progrium/ruby-jwt#subject-claim

**Comment by TiagoCardoso1983** [comment]
And I also think there's some word missing from the sentence:

> .. the for ...

I guess you mean what I call the scope in my snippet, right?

**Comment by waiting-for-dev** [comment]
Just in case somebody here is interested, I developed [warden-jwt_auth](https://github.com/waiting-for-dev/warden-jwt_auth), which is no more than a JWT Warden strategy and some rack middleware to help with token dispatching.
