### ISSUE TITLE
Warden, devise and active record session store updated_at routine

### ISSUE THREAD

**Issue by phlegx** [hassox/warden#107]
Hi!

I use Warden, Devise and ActiveRecord-Session-Store. I try to understand where the ```updated_at``` database session table attribute gets updated after a Rails request. I cannot find the begin of this routine. Is this done in Warden or Devise? Any idea? I want to add ```updated_at``` value to the session variable.

**Comment by Ralphunter** [comment]
AFAIK ActiveRecord manages the updated_at field.

**Comment by hassox** [comment]
Warden by itself does not call a save or touch on the model. I'd look into devise.
