### ISSUE TITLE
Using Warden to authenticate API: user remains authenticated across multiple requests.

### ISSUE THREAD

**Issue by hchood** [hassox/warden#111]
We're using Warden to authenticate a Rails API and I've been running into an issue where a user remains authenticated across multiple requests.  As a result, the `warden.authenticate!` is never run after the first request, so a client could pass up an invalid token or no token and get access to endpoints it shouldn't.

My solution to this problem was to explicitly logout the user before authenticating a request, but this seems a bit hacky to me and I was wondering if there is a better option.

**My Code**

```ruby
# routes.rb
Rails.application.routes.draw do
  # ...
    constraints AuthenticatedConstraint.new do
      resources :widgets
    end
  # ...
end
```
```ruby
# AuthenticatedConstraint

class AuthenticatedConstraint
  def matches?(request)
    warden = request.env['warden']
    if warden
      warden.logout if warden.authenticated? # is there a better way to do this?
      warden.authenticate!(:token_authentication_strategy)
    end
  end
end

Warden::Strategies.add(:token_authentication_strategy, TokenAuthenticationStrategy)
```
```ruby
# TokenAuthenticationStrategy

class TokenAuthenticationStrategy < ::Warden::Strategies::Base
  def valid?
    env['HTTP_AUTHORIZATION'].present?
  end

  def authenticate!
    user = User.for_authentication(token) # retrieves the user with that auth token
    if user
      success!(user)
    end
  end

  def token
    env['HTTP_AUTHORIZATION'].sub('Token token=', '')
  end
end
```

Any advice would be welcome.  Thank you!!

**Comment by TiagoCardoso1983** [comment]
I think this has to do with [this](#106), namely that Warden serializes into the session and API requests are session-less.

**Comment by hchood** [comment]
Awesome, I'll take a look!

**Comment by hassox** [comment]
You should mark your strategy as store false to prevent saving into the session.

**Comment by TiagoCardoso1983** [comment]
indeed this solves the issue, had the same problem and solved it in the same way.

**Comment by hchood** [comment]
Yes, this does, thank you!
