### ISSUE TITLE
strategy #redirect! error when url string is frozen

### ISSUE THREAD

**Issue by megatux** [hassox/warden#138]
When working on a custom Devise login strategy I found that passing a frozen url throws a 'can't modify frozen string' error.

redirect! Figaro.env.some_url

I fixed it by #dup'ing the string before calling:

redirect! Figaro.env.some_url.dup

but I think it's better to do this inside the library. I've created PR #137 for this.

**Comment by jsmestad** [comment]
Commented on #137, this is Figaro issue as it returns a frozen object. It's implementation specific so we're better off keeping warden free of things like this.
