### ISSUE TITLE
Authenticating one scope with another results in scope crossover

### ISSUE THREAD

**Issue by patrickmcguire** [hassox/warden#143]
Situation is this: I have two user classes, one of which is specific to a particular site on a network of sites, the other is global across all. They have a 1:1 relationship, one per on each site.

I want to authenticate the narrower user from the broader one, however the broader one is authenticated.

I tried a strategy like this:

```ruby
    module FromGlobalAccount 
      class FromGlobalAccountStrategy < Devise::Strategies::Authenticatable
        def valid?
           current_site_id_set # this works
        end 

        def mapping
          Devise.mappings[:user]
        end 

        def authenticate!
          global_account = env['warden'].authenticate(*GLOBAL_ACCOUNT_STRATEGIES, scope: :global_account)
          if global_account && current_site_id
            user = global_account.user_for_site_id(current_site_id)
            if user
              success!(user)
            else
              fail
            end 
          else
            fail
          end 
        end 
      end 
    end 
```

The result of this strategy running successfully is a GlobalAccount, not a User. I believe the issue is here: https://github.com/hassox/warden/blob/master/lib/warden/proxy.rb#L358

    (strategies || args).each do |name|
        strategy = _fetch_strategy(name, scope)
        next unless strategy && !strategy.performed? && strategy.valid?

         self.winning_strategy = @winning_strategies[scope] = strategy
         strategy._run!
         break if strategy.halted?
       end
    end

strategy._run! overwrites winning_strategy if there's a call to authenticate within that strategy.

Fix is flipping two lines near the end:

    strategy._run!  
    self.winning_strategy = @winning_strategies[scope] = strategy

**Comment by jsmestad** [comment]
This should now be resolved on master
