### ISSUE TITLE
Warden failure fails when using autolocales (padrino-contrib)

### ISSUE THREAD

**Issue by happycze** [hassox/warden#146]
Hi guys,
im struggling with warden authentication failure when using autolocales from padrino-contrib. Without autolocales works following gist OK, with autolocales im getting empty screen on failure.
Please see gist for details https://gist.github.com/happycze/d09e337008f8ba209d6fc54899a2ebc7

Can you help me how to setup warden (using padrino warden wrapper) to get it work?
Thank you.

**Comment by jsmestad** [comment]
@happycze this still an issue for you?

**Comment by happycze** [comment]
Not exactly, this worked for me:
`    set :warden_failure_app, proc {
      ->(env) { [ 302, {'Location' => "/#{I18n.locale}/login?error=1"}, [] ] }
    }`

**Comment by jsmestad** [comment]
Sounds good, thanks for following up!
