### ISSUE TITLE
undefined local variable or method `env' for ApplicationController:Class

### ISSUE THREAD

**Issue by cinic2003** [hassox/warden#157]
In Controller, the `env['warden']` always is undefined, but when change to `request.env['warden'],` it worked fine, the wiki said `env['warden']`,  what did I do wrong?

Any advice? Thanks

**Comment by jsmestad** [comment]
Warden docs are written as if you are using Rack directly which makes `env` available to all Rack middleware.

It sounds like you are using Rails. If that is the case, Rails wraps Rack middleware's `env` variable as a method on the `request` object.

**Comment by mattbarona** [comment]
A bit new here, so what exactly is the solution? 

instead of raise env["omniauth.auth"].to_yaml I put raise request.env ["omniauth.auth].to_yaml

Still getting an error did I understand the concept correctly?

**Comment by jsmestad** [comment]
@mattbarona I think you are referring to omniauth and not warden, correct?
