### ISSUE TITLE
Original body is not closed when `:warden` is thrown

### ISSUE THREAD

**Issue by bjeanes** [hassox/warden#82]
See [`lib/warden/manager.rb:34`](https://github.com/hassox/warden/blob/15f5dfe7444422a82ef17877d69368cb50344803/lib/warden/manager.rb#L34-L36):

``` ruby
result = catch(:warden) do
  @app.call(env)
end
```

In the case where `throw :warden` is used, a reference to the `@app`'s original body component is lost and is unable to be closed.

It is the responsibility of middleware who replace the response body to close the original response body, according to [the spec](https://github.com/rack/rack/blob/1f47a4478546602d3c17902cc3faf42b106f0638/SPEC#L223-L225). Failing to do so can cause several issues, such as orphaned resources and `ThreadError`s from deadlocks.

I found this via a `ThreadError: deadlock; recursive locking` in a Rails 3.1 application. When Rails' `threadsafe` mode is disabled (as it is by default in Rails ~> 3.1), the entire  Rack request chain is wrapped by `Rack::Lock`. As one can see, in `Rack::Lock`, [the `@mutex` is unlocked](https://github.com/rack/rack/blob/1f47a4478546602d3c17902cc3faf42b106f0638/lib/rack/lock.rb#L18) when [the body (returned wrapped by `Rack::BodyProxy`) is `close`d](https://github.com/rack/rack/blob/1f47a4478546602d3c17902cc3faf42b106f0638/lib/rack/body_proxy.rb#L18).

This is usually hidden in warden, because it is typically added to the middleware after `Rack::Lock`. However, it is still not in spec, causes other issues, and arises when the warden is used before Rails (e.g. in `config.ru` to authenticate multiple Rack/Rails applications in the same process, as is the case in the application with which I am currently working).

**Comment by jsmestad** [comment]
Closing this out given its gotten fairly stale. Still open to a PR though!
