### ISSUE TITLE
Wiki page blank for "authenticated session data"

### ISSUE THREAD

**Issue by fj** [hassox/warden#86]
At the bottom of the [Scopes](https://github.com/hassox/warden/wiki/Scopes) page is a link to [authenticated session data](https://github.com/hassox/warden/wiki/Authenticated-session-data), but this page is blank.

I couldn't find any reference to "authenticated session data" or something similar in the Warden code. Is this page valid?

**Comment by joepasq** [comment]
+1

**Comment by hassox** [comment]
He folks. How's this look: https://github.com/hassox/warden/wiki/Authenticated-session-data

**Comment by fj** [comment]
@hassox: Awesome, this looks great! Thanks for expanding.

**Comment by joepasq** [comment]
Thank you!

**Comment by JonRowe** [comment]
Useful! :)
