### ISSUE TITLE
clarification with login_as helper

### ISSUE THREAD

**Issue by mauriciopasquier** [hassox/warden#99]
Sorry if this is really obvious, but I need to confirm that I'm not doing
something wrong in my setup. I'm confused about the test helper `login_as` and
`on_next_request`. Is it intended that the user dissapears (i.e. is logged
out?) after the next request?

Are these helpers not intended for features/integrations test, where you
normally click around and make several requests in a row? In this case, do you
see something wrong with using `on_request` instead of `on_next_request`?

I don't see the rationale of making it dissapear after one request when you
could simply use `logout` after each test.

Would you accept a patch adding a `login_permanently_as` helper using
`on_request`? Or maybe a clarification in the README..

**Comment by ledestin** [comment]
I'm trying to use login_as in Capybara tests:
```ruby
    user = create :user                                                          
    login_as user, scope: :user                                                  
                                                                                 
    visit '/'                                                                    
    screenshot_and_save_page                                                     
    visit '/'                                                                    
    screenshot_and_save_page 
```

The first `visit` is authenticated, but the second isn't. So, it may work fine for a single HTTP request, but in my case I've got several (I'm using AJAX).

Is there a reason to be using `login_as` for a single request, given that you request teardown with `test_reset!`?

**Comment by hassox** [comment]
The login_as can be thought of as visiting your login page. You only should need to do it once, and after that your session should keep track of what's going on. Please confirm that you session is working correctly, and also that your mock_user is handled by the session serializers.

**Comment by ledestin** [comment]
Well, the user is serialized under `session['warden.user.user.key']` and it looks like this `[[2], "$2a$10$12TdWyIwWthkSvpiUV1h9e"]` (fields being id and encrypted password). How do I check that session is working correctly?

**Comment by ledestin** [comment]
There's nothing in the `session['warden.user.user.key']` on the second `visit` though.

**Comment by hassox** [comment]
That looks like a devise session. If it is, this might help: https://github.com/plataformatec/devise/wiki/How-To:-Test-controllers-with-Rails-3-and-4-%28and-RSpec%29

Devise does some clever things with scopes and objects. If it's devise, I'd try using their helper methods, and failing that, don't use a mock for it, use a real object (just to nail down the issue)

**Comment by ledestin** [comment]
1. The article is about controller tests, but I'm testing with Capybara, those are feature tests.
2. Devise login helpers aren't available in Capybara tests.
3. I'm not using a mock object, it is a real ActiveRecord, created with FactoryGirl.

**Comment by ledestin** [comment]
There's a Devise howto about Warden and Capybara, so I'm doing it by the book:
https://github.com/plataformatec/devise/wiki/How-To:-Test-with-Capybara

**Comment by ledestin** [comment]
@gotjosh can you please share what you did? I've tried using on_request and it did nothing for me. Thanks.

**Comment by gotjosh** [comment]
@ledestin Basically what I did was create a new function called `login_permanently_as` that does the same thing that Warden does to auth but on test. I'm almost certain this is a bad practice but here you go:
````ruby
module Warden
  module Test
    module Helpers

      def login_permanently_as(user, opts = {})
        Warden::Manager.on_request do |proxy|
          opts[:event] || :authentication
          proxy.set_user(user, opts)
        end
      end

    end
  end
end
````

**Comment by ledestin** [comment]
@gotjosh thanks! May be a bad practice, but it's 3x faster!
I've updated it a bit:
https://isntabook.mooo.com/faster-feature-spec-logins/

**Comment by micapam** [comment]
@gotjosh Thanks for that - saved my life!

**Comment by shlima** [comment]
@gotjosh you have to add following code in this case:

```ruby
 config.after :each, type: :system do
    Warden::Manager._on_request.clear
  end
```

**Comment by jlefley** [comment]
I'm running into the same issue where login_as only provides authentication for one request and I'm confused about why the solution from @gotjosh is needed. I printed the session in the controller handling the requests after calling login_as and it includes the user key but for both requests but the the second is handled as if the user is not authenticated.

Session contents from request made immediately after calling login_as:

`session_id: d3a68c592ec2df872c2255a6575ecdc3`
`warden.user.user.key: [[1], "$2a$04$JfjJsKxuWHEd3vFI6bqF8."]`

That first request passes the authentication check and behaves as if the user is signed in.

Then I make the same request again and see this in the session:

`session_id: 8d5a8e993050134583753440e4343812`
`warden.user.user.key: [[1], "$2a$04$JfjJsKxuWHEd3vFI6bqF8."]`

That second request does not pass the authentication check and behaves as if the user is not signed in.

I can use the workaround for now but I am unclear about why login_as does not work as intended. This seems to be a somewhat common problem as evidenced by this issue and https://stackoverflow.com/questions/41084378/capybara-resets-devise-session-after-each-request

**Comment by dangxuanphuc** [comment]
@gotjosh thank you very much

**Comment by drewlustro** [comment]
Lost an afternoon to this issue while trying to get Devise/Warden working with system tests. Incredible that @gotjosh's solution is relevant 8 years later.

Given "system tests" are a relatively modern recommendation, most solutions on the web are junk. Devise makes no mention and neither does Warden. Best one gets is misleading documentation on controller or feature specs.

Rails engineers truly are aging out 💀
